#ROS 2
export ROS_DISTRO=jazzy

source /opt/ros/$ROS_DISTRO/setup.bash

if [ -f "$HOME/ros_ws/install/setup.bash" ]; then
    source "$HOME/ros_ws/install/setup.bash"
fi

export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}


# Autocomplete geral do Bash
if [ -f /usr/share/bash-completion/bash-completion ]; then
    source /usr/share/bash-completion/bash-completion
fi

# Autocomplete do colcon
if [ -f /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash ]; then
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
fi


export PS1="(ROS_ID=${ROS_DOMAIN_ID}) \u@\h:\w\$ "

#alias 

alias reaload="source ~/.bashrc"

alias killros="pkill -f ros2"
